### ISSUE TITLE
numpy&python

### ISSUE THREAD

**Issue by Qingsheng-Chen** [TimeIsAFriend/KFC#1]
您好，在对您的文章和代码进行学习的时候，遇到一些问题。
想询问一下kfc.py运行所需的包版本具体是多少（如python，numpy，sklearn）

**Comment by TimeIsAFriend** [comment]
> 您好，在对您的文章和代码进行学习的时候，遇到一些问题。 想询问一下kfc.py运行所需的包版本具体是多少（如python，numpy，sklearn）

Hi, thanks for your message.
Currently, I am using
python 3.9
numpy 1.22.4
sklearn 1.3.1

**Comment by Qingsheng-Chen** [comment]
thanks！
